version: '3.8'

services:
  todo-api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./todo-api:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
